book:
    title:            "Mapping the Open Spending Data Community"
    author:           "Anders Pedersen & Lucy Chambers"
    edition:          "First edition"
    language:         en
    publication_date: ~

    generator: { name: easybook, version: 4.8 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: introduction.md }
#        - { element: chapter, number: 1.1, content: map.md }
#        - { element: chapter, number: 1.2, content: timeline.md }
        - { element: chapter, number: 1.3, content: executive-summary.md }
        - { element: chapter, number: 2, content: case-studies-budgets.md }
        - { element: chapter, number: 2.1, content: lost-money.md }
        - { element: chapter, number: 2.2, content: openbudgetoakland.md }
        - { element: chapter, number: 2.3, content: cbga.md }
        - { element: chapter, number: 2.4, content: bosnia.md }
        - { element: chapter, number: 2.5, content: expert-grup.md }
        - { element: chapter, number: 3, content: case-studies-spending.md }
        - { element: chapter, number: 3.1, content: caring-for-my-neighbourhood.md }
        - { element: chapter, number: 3.2, content: okfn-greece.md }
        - { element: chapter, number: 3.3, content: eu-spending-data.md }
        - { element: chapter, number: 3.4, content: farmsubsidy.md }
        - { element: chapter, number: 3.5, content: farm-subsidies-mexico.md }
        - { element: chapter, number: 3.6, content: india-spend.md }
        - { element: chapter, number: 3.7, content: supervizor.md }
        - { element: chapter, number: 4, content: case-studies-procurements.md }
        - { element: chapter, number: 4.1, content: hutspace.md }
        - { element: chapter, number: 4.2, content: texty.md }
        - { element: chapter, number: 4.3, content: opented.md }
        - { element: chapter, number: 5, content: case-studies-other.md }
        - { element: chapter, number: 5.1, content: openspending.md }
        - { element: chapter, number: 5.2, content: opening-university.md }
        - { element: chapter, number: 6, content: conclusions.md }
        - { element: appendix, number: A , content: appendix.md }
        - { element: appendix, number: B , content: appendix-open-budgets-open-data.md }
        - { element: appendix, number: C , content: tool-ecosystem.md }
        - { element: appendix, number: D , content: machinereadfaq.md }
        - { element: appendix, number: E , content: privacyguide.md }
        - { element: appendix, number: F , content: other-handy-datasets.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
